from django.conf.urls import include, url
from . import views
from django.urls import include, path
from django.views.generic import TemplateView

app_name ='personajes'
urlpatterns = [
    url(r'^corrin/$',views.corrin, name="corrin"),
    url(r'^cloud/$',views.cloud, name="cloud"),
    url(r'^ike/$',views.ike, name="ike"),
    url(r'^inkling/$',views.inkling, name="inkling"),
    url(r'^joker/$',views.joker, name="joker"),
    url(r'^lucina/$',views.lucina, name="lucina"),
    url(r'^marth/$',views.marth, name="marth"),
    url(r'^pit/$',views.pit, name="pit"),
    url(r'^roy/$',views.roy, name="roy"),
    url(r'^chrom/$',views.chrom, name="chrom"),
    url(r'^bayonetta/$',views.Bayonetta, name="Bayonetta"),
    url(r'^bowser/$',views.Bowser, name="Bowser"),
    url(r'^daisy/$',views.Daisy, name="Daisy"),
    url(r'^dark_samus/$',views.Dark_samus, name="Dark_samus"),
    url(r'^diddy_kong/$',views.Diddy_kong, name="Diddy_kong"),
    url(r'^donkey_kong/$',views.Donkey_kong, name="Donkey_kong"),
    url(r'^dr_mario/$',views.Dr_mario, name="Dr_mario"),
    url(r'^duck_hunt/$',views.Duck_hunt, name="Duck_hunt"),
    url(r'^falco/$',views.falco, name="falco"),
    url(r'^fox/$',views.fox, name="fox"),
    url(r'^ganondorf/$',views.ganondorf, name="ganondorf"),
    url(r'^greninja/$',views.greninja, name="greninja"),
    url(r'^hero/$',views.hero, name="hero"),
    url(r'^ice_climbers/$',views.ice_climbers, name="ice_climbers"),
    url(r'^/$',views.robin, name="robin"),
    url(r'^incineroar/$',views.incineroar, name="incineroar"),
    url(r'^isabelle/$',views.isabelle, name="isabelle"),
    url(r'^jigglypuff/$',views.jigglypuff, name="jigglypuff"),
    url(r'^ken/$',views.ken, name="ken"),
    url(r'^king_dedede/$',views.king_dedede, name="king_dedede"),
    url(r'^king_k_rool/$',views.king_k_rool, name="king_k_rool"),
    url(r'^kirby/$',views.kirby, name="kirby"),
    url(r'^little_mac/$',views.little_mac, name="little_mac"),
    url(r'^lucario/$',views.lucario, name="lucario"),
    url(r'^lucas/$',views.lucas, name="lucas"),
    url(r'^luigi/$',views.luigi, name="luigi"),
    url(r'^mario/$',views.mario, name="mario"),
    url(r'^mega_man/$',views.mega_man, name="mega_man"),
    url(r'^meta_knight/$',views.meta_knight, name="meta_knight"),
    url(r'^mewtwo/$',views.mewtwo, name="mewtwo"),
    url(r'^mr_game_and_watch/$',views.mr_game_and_watch, name="mr_game_and_watch"),
    url(r'^ness/$',views.ness, name="ness"),
    url(r'^olimar/$',views.olimar, name="olimar"),
    url(r'^pac_man/$',views.pac_man, name="pac_man"),
    url(r'^palutena/$',views.palutena, name="palutena"),
    url(r'^peach/$',views.peach, name="peach"),
    url(r'^pichu/$',views.pichu, name="pichu"),
    url(r'^pikachu/$',views.pikachu, name="pikachu"),
    url(r'^piranha_plant/$',views.piranha_plant, name="piranha_plant"),
    url(r'^pt_charizard/$',views.pt_charizard, name="pt_charizard"),
    url(r'^pt_ivysaur/$',views.pt_ivysaur, name="pt_ivysaur"),
    url(r'^pt_squirtle/$',views.pt_squirtle, name="pt_squirtle"),
    url(r'^richter/$',views.richter, name="richter"),
    url(r'^ridley/$',views.ridley, name="ridley"),
    url(r'^ryu/$',views.ryu, name="ryu"),
    url(r'^samus/$',views.samus, name="samus"),
    url(r'^simon/$',views.simon, name="simon"),
    url(r'^snake/$',views.snake, name="snake"),
    url(r'^sonic/$',views.sonic, name="sonic"),
    url(r'^terry/$',views.terry, name="terry"),
    url(r'^wolf/$',views.wolf, name="wolf"),
    url(r'^young_link/$',views.young_link, name="young_link"),
  



]