# Generated by Django 2.2.7 on 2019-11-29 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191111_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('admin', 'Es administrador'), ('usuario', 'Es usuario'))},
        ),
    ]
